version: '3.8'
services:
  db:
    image: postgres:15
    container_name: devicedb
    environment:
      POSTGRES_DB: devicedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123321
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  dev-api:
    build: .
    container_name: dev-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devicedb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123321

  test:
    build:
      context: .
      target: build
    container_name: dev-api-test
    depends_on:
      - db
    entrypoint: ["mvn", "test"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devicedb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123321

volumes:
  pgdata:
